//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SisClinicaModel11", "fkReporteDetalle_Reporte", "Reporte", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BaseR.Reporte), "ReporteDetalle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BaseR.ReporteDetalle), true)]

#endregion

namespace BaseR
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ReporteEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ReporteEntities object using the connection string found in the 'ReporteEntities' section of the application configuration file.
        /// </summary>
        public ReporteEntities() : base("name=ReporteEntities", "ReporteEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ReporteEntities object.
        /// </summary>
        public ReporteEntities(string connectionString) : base(connectionString, "ReporteEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ReporteEntities object.
        /// </summary>
        public ReporteEntities(EntityConnection connection) : base(connection, "ReporteEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Reporte> Reporte
        {
            get
            {
                if ((_Reporte == null))
                {
                    _Reporte = base.CreateObjectSet<Reporte>("Reporte");
                }
                return _Reporte;
            }
        }
        private ObjectSet<Reporte> _Reporte;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ReporteDetalle> ReporteDetalle
        {
            get
            {
                if ((_ReporteDetalle == null))
                {
                    _ReporteDetalle = base.CreateObjectSet<ReporteDetalle>("ReporteDetalle");
                }
                return _ReporteDetalle;
            }
        }
        private ObjectSet<ReporteDetalle> _ReporteDetalle;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Reporte EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReporte(Reporte reporte)
        {
            base.AddObject("Reporte", reporte);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ReporteDetalle EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReporteDetalle(ReporteDetalle reporteDetalle)
        {
            base.AddObject("ReporteDetalle", reporteDetalle);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SisClinicaModel11", Name="Reporte")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Reporte : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Reporte object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="orden">Initial value of the Orden property.</param>
        /// <param name="codigo">Initial value of the Codigo property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        /// <param name="filtro">Initial value of the Filtro property.</param>
        /// <param name="mostrarPivot">Initial value of the MostrarPivot property.</param>
        /// <param name="filtroFecha">Initial value of the FiltroFecha property.</param>
        public static Reporte CreateReporte(global::System.Int32 id, global::System.String orden, global::System.String codigo, global::System.String descripcion, global::System.Boolean filtro, global::System.Boolean mostrarPivot, global::System.Boolean filtroFecha)
        {
            Reporte reporte = new Reporte();
            reporte.ID = id;
            reporte.Orden = orden;
            reporte.Codigo = codigo;
            reporte.Descripcion = descripcion;
            reporte.Filtro = filtro;
            reporte.MostrarPivot = mostrarPivot;
            reporte.FiltroFecha = filtroFecha;
            return reporte;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Orden
        {
            get
            {
                return _Orden;
            }
            set
            {
                OnOrdenChanging(value);
                ReportPropertyChanging("Orden");
                _Orden = StructuralObject.SetValidValue(value, false, "Orden");
                ReportPropertyChanged("Orden");
                OnOrdenChanged();
            }
        }
        private global::System.String _Orden;
        partial void OnOrdenChanging(global::System.String value);
        partial void OnOrdenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                OnCodigoChanging(value);
                ReportPropertyChanging("Codigo");
                _Codigo = StructuralObject.SetValidValue(value, false, "Codigo");
                ReportPropertyChanged("Codigo");
                OnCodigoChanged();
            }
        }
        private global::System.String _Codigo;
        partial void OnCodigoChanging(global::System.String value);
        partial void OnCodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false, "Descripcion");
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Query
        {
            get
            {
                return _Query;
            }
            set
            {
                OnQueryChanging(value);
                ReportPropertyChanging("Query");
                _Query = StructuralObject.SetValidValue(value, true, "Query");
                ReportPropertyChanged("Query");
                OnQueryChanged();
            }
        }
        private global::System.String _Query;
        partial void OnQueryChanging(global::System.String value);
        partial void OnQueryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] ConfXml1
        {
            get
            {
                return StructuralObject.GetValidValue(_ConfXml1);
            }
            set
            {
                OnConfXml1Changing(value);
                ReportPropertyChanging("ConfXml1");
                _ConfXml1 = StructuralObject.SetValidValue(value, true, "ConfXml1");
                ReportPropertyChanged("ConfXml1");
                OnConfXml1Changed();
            }
        }
        private global::System.Byte[] _ConfXml1;
        partial void OnConfXml1Changing(global::System.Byte[] value);
        partial void OnConfXml1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] ConfXml2
        {
            get
            {
                return StructuralObject.GetValidValue(_ConfXml2);
            }
            set
            {
                OnConfXml2Changing(value);
                ReportPropertyChanging("ConfXml2");
                _ConfXml2 = StructuralObject.SetValidValue(value, true, "ConfXml2");
                ReportPropertyChanged("ConfXml2");
                OnConfXml2Changed();
            }
        }
        private global::System.Byte[] _ConfXml2;
        partial void OnConfXml2Changing(global::System.Byte[] value);
        partial void OnConfXml2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Filtro
        {
            get
            {
                return _Filtro;
            }
            set
            {
                OnFiltroChanging(value);
                ReportPropertyChanging("Filtro");
                _Filtro = StructuralObject.SetValidValue(value, "Filtro");
                ReportPropertyChanged("Filtro");
                OnFiltroChanged();
            }
        }
        private global::System.Boolean _Filtro;
        partial void OnFiltroChanging(global::System.Boolean value);
        partial void OnFiltroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FormFiltro
        {
            get
            {
                return _FormFiltro;
            }
            set
            {
                OnFormFiltroChanging(value);
                ReportPropertyChanging("FormFiltro");
                _FormFiltro = StructuralObject.SetValidValue(value, true, "FormFiltro");
                ReportPropertyChanged("FormFiltro");
                OnFormFiltroChanged();
            }
        }
        private global::System.String _FormFiltro;
        partial void OnFormFiltroChanging(global::System.String value);
        partial void OnFormFiltroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean MostrarPivot
        {
            get
            {
                return _MostrarPivot;
            }
            set
            {
                OnMostrarPivotChanging(value);
                ReportPropertyChanging("MostrarPivot");
                _MostrarPivot = StructuralObject.SetValidValue(value, "MostrarPivot");
                ReportPropertyChanged("MostrarPivot");
                OnMostrarPivotChanged();
            }
        }
        private global::System.Boolean _MostrarPivot;
        partial void OnMostrarPivotChanging(global::System.Boolean value);
        partial void OnMostrarPivotChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean FiltroFecha
        {
            get
            {
                return _FiltroFecha;
            }
            set
            {
                OnFiltroFechaChanging(value);
                ReportPropertyChanging("FiltroFecha");
                _FiltroFecha = StructuralObject.SetValidValue(value, "FiltroFecha");
                ReportPropertyChanged("FiltroFecha");
                OnFiltroFechaChanged();
            }
        }
        private global::System.Boolean _FiltroFecha;
        partial void OnFiltroFechaChanging(global::System.Boolean value);
        partial void OnFiltroFechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ColumnFecha
        {
            get
            {
                return _ColumnFecha;
            }
            set
            {
                OnColumnFechaChanging(value);
                ReportPropertyChanging("ColumnFecha");
                _ColumnFecha = StructuralObject.SetValidValue(value, true, "ColumnFecha");
                ReportPropertyChanged("ColumnFecha");
                OnColumnFechaChanged();
            }
        }
        private global::System.String _ColumnFecha;
        partial void OnColumnFechaChanging(global::System.String value);
        partial void OnColumnFechaChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SisClinicaModel11", "fkReporteDetalle_Reporte", "ReporteDetalle")]
        public EntityCollection<ReporteDetalle> ReporteDetalle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ReporteDetalle>("SisClinicaModel11.fkReporteDetalle_Reporte", "ReporteDetalle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ReporteDetalle>("SisClinicaModel11.fkReporteDetalle_Reporte", "ReporteDetalle", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SisClinicaModel11", Name="ReporteDetalle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ReporteDetalle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ReporteDetalle object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="iDReporte">Initial value of the IDReporte property.</param>
        /// <param name="numero">Initial value of the Numero property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="caption">Initial value of the Caption property.</param>
        /// <param name="tipoInterno">Initial value of the TipoInterno property.</param>
        public static ReporteDetalle CreateReporteDetalle(global::System.Int32 id, global::System.Int32 iDReporte, global::System.Int32 numero, global::System.String name, global::System.String caption, global::System.String tipoInterno)
        {
            ReporteDetalle reporteDetalle = new ReporteDetalle();
            reporteDetalle.ID = id;
            reporteDetalle.IDReporte = iDReporte;
            reporteDetalle.Numero = numero;
            reporteDetalle.Name = name;
            reporteDetalle.Caption = caption;
            reporteDetalle.TipoInterno = tipoInterno;
            return reporteDetalle;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDReporte
        {
            get
            {
                return _IDReporte;
            }
            set
            {
                OnIDReporteChanging(value);
                ReportPropertyChanging("IDReporte");
                _IDReporte = StructuralObject.SetValidValue(value, "IDReporte");
                ReportPropertyChanged("IDReporte");
                OnIDReporteChanged();
            }
        }
        private global::System.Int32 _IDReporte;
        partial void OnIDReporteChanging(global::System.Int32 value);
        partial void OnIDReporteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Numero
        {
            get
            {
                return _Numero;
            }
            set
            {
                OnNumeroChanging(value);
                ReportPropertyChanging("Numero");
                _Numero = StructuralObject.SetValidValue(value, "Numero");
                ReportPropertyChanged("Numero");
                OnNumeroChanged();
            }
        }
        private global::System.Int32 _Numero;
        partial void OnNumeroChanging(global::System.Int32 value);
        partial void OnNumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FieldName
        {
            get
            {
                return _FieldName;
            }
            set
            {
                OnFieldNameChanging(value);
                ReportPropertyChanging("FieldName");
                _FieldName = StructuralObject.SetValidValue(value, true, "FieldName");
                ReportPropertyChanged("FieldName");
                OnFieldNameChanged();
            }
        }
        private global::System.String _FieldName;
        partial void OnFieldNameChanging(global::System.String value);
        partial void OnFieldNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Caption
        {
            get
            {
                return _Caption;
            }
            set
            {
                OnCaptionChanging(value);
                ReportPropertyChanging("Caption");
                _Caption = StructuralObject.SetValidValue(value, false, "Caption");
                ReportPropertyChanged("Caption");
                OnCaptionChanged();
            }
        }
        private global::System.String _Caption;
        partial void OnCaptionChanging(global::System.String value);
        partial void OnCaptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TipoInterno
        {
            get
            {
                return _TipoInterno;
            }
            set
            {
                OnTipoInternoChanging(value);
                ReportPropertyChanging("TipoInterno");
                _TipoInterno = StructuralObject.SetValidValue(value, false, "TipoInterno");
                ReportPropertyChanged("TipoInterno");
                OnTipoInternoChanged();
            }
        }
        private global::System.String _TipoInterno;
        partial void OnTipoInternoChanging(global::System.String value);
        partial void OnTipoInternoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SisClinicaModel11", "fkReporteDetalle_Reporte", "Reporte")]
        public Reporte Reporte
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reporte>("SisClinicaModel11.fkReporteDetalle_Reporte", "Reporte").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reporte>("SisClinicaModel11.fkReporteDetalle_Reporte", "Reporte").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Reporte> ReporteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reporte>("SisClinicaModel11.fkReporteDetalle_Reporte", "Reporte");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Reporte>("SisClinicaModel11.fkReporteDetalle_Reporte", "Reporte", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
